# Generated by Django 3.2 on 2021-05-03 08:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=50)),
                ('jobType', models.CharField(max_length=50)),
                ('jobLocation', models.CharField(max_length=50)),
                ('jobDescription', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('jobPublishedDate', models.DateTimeField()),
                ('jobVacancy', models.IntegerField()),
            ],
        ),
    ]
